# -*- coding: utf-8 -*-
"""Python error types checkpoint.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13lsL-OM_7rDaTaVTc6VXDn-x7cMkVCGG

# Rectify the code in each cell and **explain the error in comments**

### index error
"""

mylist=[14, "hello", 967]
element=mylist[1]
print(element)

import pandas
import numpy

"""# syntax error"""

print("Python errors")

"""# key error"""

mydictionary = {True: "hello" , False: "bye" , "3" : "python"}
value = mydictionary['3']
print(value)

"""# indentation error"""

i = 14
while i < 78:
    print(i)
    i +=1

"""# StopIteration"""

it = iter([1,2,3])
print(next(it))
print(next(it))
print(next(it))

"""# TypeError

"""

result = "15" + str(15)
print(result)

"""# ValueError"""

int('123')

"""# NameError"""



"""# ZeroDivisionError"""

x = 19